apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: tunnel
        image: resolt123/terbangin:CF
        command: ["cloudflared","tunnel", "run", "richard-be"]
        env:
        - name: TUNNEL_TOKEN
          value: "eyJhIjoiMWMzYzA5ODY2ZjU0ZDNkNzkzYTg0NzEwOGI0N2RiZjUiLCJ0IjoiZWJiMDNmOTctZGQ2Zi00NzA3LWExZjMtMjBkMzUzNjgzZGViIiwicyI6IlltTmxaVGt6TVRRdE16VTNZeTAwWkRJNExXSTBNV0V0TW1FeFltVTFZVGt5T1RWbCJ9"
